package demolition.element;

import demolition.Grid;
import demolition.util.TimeOutHandler;
import demolition.util.Timer;

/**
 * The base class for all elements that live over the background and have animation
 * including bomb guy, bomb, enemy, and the fire generated by the bomb
 */
public abstract class Element {
    /**
     * register a timeout event to the event
     * @param timer the timer, which is from the Grid class
     * @param interval count of frames passed before the event happens
     * @param handler the event handler of the timeout event
     */
    protected void registerTimerEvent(Timer timer, int interval, TimeOutHandler handler){
        timer.register(interval, this, handler);
    }

    /**
     *
     * @return the image key anem for the ImageCollection to get the corresponding PImage file to draw on the canvas
     */
    public abstract String getCurrentImageKey();

    /**
     * The method happened when the element is bombed
     */
    public void onBombed() {}
    protected Grid grid;
    public Element(Grid grid) {
        this.grid = grid;
    }

    /**
     * Indicate if the element is harmful to the bomb guy
     * @return true if harmful
     */
    public boolean isHarmful() { return false; }
}
